# Copyright (c) 2026 Robotics and AI Institute LLC dba RAI Institute. All rights reserved.

name: Test

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}-${{ github.ref == 'refs/heads/main' && github.sha || ''}}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test-export:
    name: Test Export Core Package
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: core

      - name: Run Tests
        run: pixi run -e core test

      - name: Run Python Linting
        run: pixi run -e core lint

      - name: Check Python Formatting
        run: pixi run -e core format-python-check

  test-controller:
    name: Test Controller Environment
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: controller

      - name: Setup Controller Environment
        run: pixi run -e controller setup

      - name: Build Controller
        run: pixi run -e controller build

      - name: Run Controller Tests
        run: pixi run -e controller test

      - name: Check Formatting
        run: pixi run -e controller format-check


  test-isaaclab-export:
    name: Test Export IsaacLab
    runs-on: github-gpu-runner
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: isaaclab

      - name: Run Isaac Lab Export Test
        env:
          OMNI_KIT_ACCEPT_EULA: yes
        run: pixi run -e isaaclab export-isaaclab-ci


  test-frameworks-isaaclab:
    name: Test Frameworks - IsaacLab
    runs-on: github-gpu-runner
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: latest
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          environments: isaaclab

      - name: Run Frameworks IsaacLab Tests
        env:
          OMNI_KIT_ACCEPT_EULA: yes
        run: pixi run -e isaaclab test
